encoder:
  model_path: "sentence-transformers/multi-qa-mpnet-base-dot-v1"

  model_kwargs: 
    device: "cpu"

  encode_kwargs:
    normalize_embeddings: False
  
transcriptor:
  model: "base"
  device: "cpu"
