encoder:
  model_path: "sentence-transformers/multi-qa-mpnet-base-dot-v1"

  model_kwargs: 
    device: "cpu"

  encode_kwargs:
    normalize_embeddings: False
  
transcriptor:
  model: "base"
  device: "cpu"

generator:
  llm_path: "model/nous-hermes-llama-2-7b.Q4_0.gguf"
  context_length: 1024
  temperature: 0.7
  max_tokens: 5000